### ISSUE TITLE
`TypeError: Cannot read properties of null (reading 'r')`

### ISSUE THREAD

**Issue by gustavopch** [askorama/orama#773]
### Describe the bug

```
Rebalancing tree after 10 inserts...
Rebalancing tree after 10 inserts...
Rebalancing tree after 10 inserts...
Rebalancing tree after 10 inserts...
Rebalancing tree after 10 inserts...
Rebalancing tree after 10 inserts...
Rebalancing tree after 10 inserts...
Rebalancing tree after 14 inserts...
/Users/<omitted>/node_modules/@orama/orama/src/trees/avl.ts:32
  node.l = left.r
                ^


TypeError: Cannot read properties of null (reading 'r')
    at rotateRight (/Users/<omitted>/node_modules/@orama/orama/src/trees/avl.ts:32:17)
    at rebalanceNode (/Users/<omitted>/node_modules/@orama/orama/src/trees/avl.ts:259:14)
    at insertNode (/Users/<omitted>/node_modules/@orama/orama/src/trees/avl.ts:231:14)
    at insertNode (/Users/<omitted>/node_modules/@orama/orama/src/trees/avl.ts:219:16)
    at insertNode (/Users/<omitted>/node_modules/@orama/orama/src/trees/avl.ts:219:16)
    at insertNode (/Users/<omitted>/node_modules/@orama/orama/src/trees/avl.ts:217:16)
    at insert (/Users/<omitted>/node_modules/@orama/orama/src/trees/avl.ts:237:19)
    at insertScalar (/Users/<omitted>/node_modules/@orama/orama/src/components/index.ts:311:9)
    at Object.insert (/Users/<omitted>/node_modules/@orama/orama/src/components/index.ts:357:12)
    at innerInsert (/Users/<omitted>/node_modules/@orama/orama/src/methods/insert.ts:111:23)
```

### To Reproduce

```ts
// My actual case has ~16k numbers. I simplified as much as I could in this repro.
const numbers = [
  67,
  39,
  43,
  6,
  38169669,
  47538267,
  82170842,
  84974929,
  87328229,
  87783955,
  91430475,
  91577672,
  99241484,
  3521742,
  88,
  37,
  78,
]

const index = await create({
  schema: {
    number: 'number',
  } as const,
})

await insertMultiple(
  index,
  numbers.map(number => ({
    number: number,
  })),
  10,
)
```

### Expected behavior

Shouldn't crash.

### Environment Info

```bash
macOS v14.6.1
Node.js v22.6.0
Orama v2.0.23
```

### Affected areas

Data Insertion

**Comment by micheleriva** [comment]
Fixed in #777

**Comment by gustavopch** [comment]
@micheleriva That PR removes the log. I think it doesn’t fix this error.
